"use client";
import { useState } from "react";
import { GAME_SERVER_PRESETS, gamePresetEnvErrors, gameImageError, gameSummaryEnv, isSensitiveGameEnv, type GameServerPreset } from "@/lib/game-server-presets";
import { currentTeam, switchTeam } from "@/lib/api";
import { TeamSelect } from "@/components/team-picker";
import { Card, Button, Input } from "@/components/ui";
export type GameDeployOptions = { image: string; project: string; port: number; protocol: string; memory: string; ports: { container_port: number; protocol: string; label?: string }[]; env: Record<string, string>; volumeMountPath: string };
export function GamesMenu({ onSelect, disabled }: { onSelect: (game: GameServerPreset) => void; disabled: boolean }) {
  return <details className="mb-8 rounded-xl border border-border p-4" open><summary className="cursor-pointer text-lg font-semibold">Games — dedicated hosting</summary><p className="my-3 text-sm text-secondary">Choose a game, then configure a supported profile. Catalog only: registry availability, capacity and game connectivity are not verified.</p><nav aria-label="Games" className="grid gap-2 sm:grid-cols-2">{GAME_SERVER_PRESETS.map(game => <button type="button" key={game.gameId} disabled={disabled} onClick={() => onSelect(game)} className="rounded-lg border border-border p-3 text-left hover:bg-subtle"><span className="font-semibold">{game.name}</span><span className="mt-1 block text-xs text-secondary">{game.protocol.toUpperCase()} {game.port}{game.extraPorts?.length ? " + " + game.extraPorts.length + " ports (direct ingress required)" : ""} · {game.memory} requested · {game.volumeMountPath}</span></button>)}</nav></details>;
}
export function ConfigureGame({ game, onBack, onCreate, deploying, error }: { game: GameServerPreset; onBack: () => void; onCreate: (opts: GameDeployOptions) => void; deploying: boolean; error: string }) {
  const [env, setEnv] = useState<Record<string, string>>({ ...game.env });
  const [image, setImage] = useState(game.image);
  const [name, setName] = useState(game.gameId ?? "game-server");
  const [memory, setMemory] = useState(game.memory);
  const [team, setTeam] = useState(currentTeam());
  const [profile, setProfile] = useState("");
  const [stage, setStage] = useState<"configure" | "review">("configure");
  const [ready, setReady] = useState(false);
  const [ingress, setIngress] = useState(false);
  const [submitError, setSubmitError] = useState("");
  const ports = [{ container_port: game.port, protocol: game.protocol }, ...(game.extraPorts ?? []).map(p => ({ container_port: p.port, protocol: p.protocol, label: p.label }))];
  const errors = [...gamePresetEnvErrors(game, env)];
  const imageError = gameImageError(game, image); if (imageError) errors.push(imageError);
  if (!/^[a-z0-9][a-z0-9-]{0,62}$/.test(name)) errors.push("Project name must be 1–63 lowercase letters, numbers or hyphens.");
  if (!/^\d+(\.\d+)?[mg]$/i.test(memory)) errors.push("Memory requires a positive m/g quantity.");
  if (parseFloat(memory) <= 0) errors.push("Memory must be positive.");
  const canReview = !errors.length && ready && (!game.extraPorts?.length || ingress);
  const update = (key: string, value: string) => setEnv(old => ({ ...old, [key]: value }));
  async function submit() {
    if (!canReview || deploying || stage !== "review") return;
    try { await switchTeam(team === "personal" ? "__personal__" : team); onCreate({ image, project: name, port: game.port, protocol: game.protocol, memory, ports, env, volumeMountPath: game.volumeMountPath }); } catch { setSubmitError("Could not select team. No deployment submitted."); }
  }
  return <div className="mx-auto max-w-3xl"><button type="button" disabled={deploying} onClick={onBack} className="mb-4 text-sm underline">← Back to Games</button><Card className="p-6"><h1 className="text-2xl font-semibold">Configure {game.name}</h1><p className="my-3 text-sm text-secondary">{game.desc}</p><section aria-label="Hosting readiness" className="mb-5 rounded-lg border border-border p-4"><h2 className="font-semibold">Hosting readiness</h2><p className="text-sm">Platform: {game.platform} · Memory request: {memory} · Persistence: {game.volumeMountPath}</p><p className="text-sm">Public container ports: {ports.map(p => p.container_port + "/" + p.protocol.toUpperCase()).join(", ")}. Allocated public ports may differ.</p><p className="my-2 text-sm">{game.runtimeVersionNote}</p><ul className="list-disc space-y-1 pl-5 text-xs text-secondary">{game.setupNotes.map(note => <li key={note}>{note}</li>)}</ul><p role="note" className="mt-3 text-sm text-amber-600">Credential deployment requires the updated native backend secret policy. The current local backend has not been upgraded; do not enter real credentials or deploy them there. UI publication alone does not make it safe.</p></section>
  {stage === "configure" ? <>
    <div className="grid gap-4 sm:grid-cols-2"><label>Project name<Input aria-label="Project name" value={name} onChange={e => setName(e.target.value)} /></label><div><span className="block text-sm">Team</span><TeamSelect value={team} onChange={setTeam} /></div><label>Requested memory<Input aria-label="Requested memory" value={memory} onChange={e => setMemory(e.target.value)} /></label><label>Supported profile<select aria-label="Supported profile" className="block w-full rounded border border-border bg-card p-2" value={profile} onChange={e => { const p = game.profiles?.find(p => p.id === e.target.value); setProfile(e.target.value); if(p) setEnv(old => ({ ...old, ...p.env })); }}><option value="">Existing defaults / custom settings</option>{game.profiles?.map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select></label></div>
    <fieldset className="my-5"><legend className="font-semibold">OCI image version (not runtime game version)</legend><label>Documented image channel<select aria-label="Documented image channel" className="block rounded border border-border bg-card p-2" value={game.imageTags?.includes(image.split(":").pop() ?? "") ? image.split(":").pop() : "custom"} onChange={e => { if(e.target.value !== "custom") setImage(game.image.replace(/:[^/:]+$/, ":" + e.target.value)); }}><option value="custom">Custom tag / digest</option>{game.imageTags?.map(tag => <option key={tag} value={tag}>{tag}</option>)}</select></label><label className="mt-2 block">Audited repository image reference<Input aria-label="Audited repository image reference" value={image} onChange={e => setImage(e.target.value)} /></label><p className="text-xs text-secondary">Custom tags/digests are syntax-checked only. Verify registry existence, platform and compatibility before use. No invented release list.</p></fieldset>
    <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-semibold">{game.name} settings</legend>{game.fields?.map(f => <label key={f.key} htmlFor={"game-" + f.key} className="text-sm">{f.label}{f.kind === "select" ? <select id={"game-" + f.key} className="block w-full rounded border border-border bg-card p-2" value={env[f.key] ?? ""} onChange={e => update(f.key,e.target.value)}><option value="">Upstream default</option>{f.options?.map(v => <option key={v} value={v}>{v}</option>)}</select> : <Input id={"game-" + f.key} autoComplete="off" type={f.kind === "secret" ? "password" : f.kind === "integer" ? "number" : "text"} min={f.min} max={f.max} value={env[f.key] ?? ""} onChange={e => update(f.key,e.target.value)} />}{f.help && <span className="mt-1 block text-xs text-secondary">{f.help}</span>}</label>)}</fieldset>
    <details className="my-5"><summary className="cursor-pointer">Advanced environment variables (credentials masked)</summary><p className="text-xs">Typed and transport keys are controlled above or fixed to audited ports. No config export.</p>{Object.entries(env).filter(([key]) => !game.fields?.some(f => f.key === key) && Object.hasOwn(game.env,key)).map(([key,value]) => <label className="mt-2 block text-sm" key={key}>{key}<Input aria-label={key} type={isSensitiveGameEnv(key) ? "password" : "text"} value={value} disabled={/(PORT|RCON|REST_API|SUPERVISOR|STATUS_HTTP|COMMUNITY|LOG_LEVEL|STEAM_LOGIN)/.test(key)} onChange={e => update(key,e.target.value)} /></label>)}<label className="mt-3 block">Additional key<Input aria-label="Additional environment key" id="additional-game-key" placeholder="CUSTOM_KEY" /></label><Button variant="outline" onClick={() => { const input = document.getElementById("additional-game-key") as HTMLInputElement; const key = input.value.trim(); if (/^[A-Z][A-Z0-9_]*$/.test(key) && !Object.hasOwn(env,key) && !game.fields?.some(f => f.key === key) && !/(PORT|RCON|REST_API|SUPERVISOR|STATUS_HTTP|COMMUNITY|LOG_LEVEL)/.test(key)) { update(key, ""); input.value = ""; } }}>Add advanced key</Button>{Object.entries(env).filter(([key]) => !Object.hasOwn(game.env,key) && !game.fields?.some(f => f.key === key)).map(([key,value]) => <label className="mt-2 block" key={key}>{key}<Input aria-label={"Advanced " + key} autoComplete="off" type={isSensitiveGameEnv(key) ? "password" : "text"} value={value} onChange={e => update(key,e.target.value)} /></label>)}</details>
    <label className="my-3 flex gap-2 text-sm"><input type="checkbox" checked={ready} onChange={e => setReady(e.target.checked)} />I verified image/node platform, disk/memory capacity, persistent volume/backup readiness and updated backend credential protection.</label>
    {!!game.extraPorts?.length && <label className="my-3 flex gap-2 text-sm"><input type="checkbox" checked={ingress} onChange={e => setIngress(e.target.checked)} />I verified direct serving-node ingress for every port. mesh_raw routes only the primary port; mesh-only hosting is not ready.</label>}
    {!!errors.length && <p role="alert" className="my-3 text-sm text-red-600">{errors.join(" ")}</p>}<Button disabled={!canReview || deploying} onClick={() => setStage("review")}>Review configuration</Button>
  </> : <section aria-label="Deployment summary"><h2 className="text-lg font-semibold">Review before creating</h2><p>{name} · Team: {team} · {memory} requested</p><p className="break-all font-mono text-xs">{image}</p><p>{ports.map(p => p.container_port + "/" + p.protocol).join(", ")} · Persistent {game.volumeMountPath}</p><dl className="my-4 text-xs">{gameSummaryEnv(env).map(row => <div key={row.key} className="flex gap-3"><dt>{row.key}</dt><dd className="break-all">{row.value || "Upstream default / empty"}</dd></div>)}</dl><p className="my-3 text-sm">No game launch, registry pull, port reachability or capacity approval has been proven by this review.</p><Button variant="outline" disabled={deploying} onClick={() => setStage("configure")}>Back to configuration</Button><Button disabled={!canReview || deploying} onClick={submit}>{deploying ? "Creating…" : "Create game server"}</Button></section>}
  {(error || submitError) && <p role="alert" className="mt-3 text-sm text-red-600">Deployment failed. Check private operator logs; raw server errors are not shown here.{submitError}</p>}
  </Card></div>;
}
