var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/github/disconnect/route.js")
R.c("server/chunks/[root-of-the-server]__1s0r82e._.js")
R.c("server/chunks/lib_composio_ts_1qgq01_._.js")
R.c("server/chunks/[root-of-the-server]__193d3s6._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/_next-internal_server_app_api_github_disconnect_route_actions_0m2v6_b.js")
R.m(49561)
module.exports=R.m(49561).exports
