// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/activity" | "/admin" | "/admin/audit" | "/admin/data" | "/admin/databases" | "/admin/incidents" | "/admin/nodes" | "/admin/teams" | "/billing" | "/billing/checkout" | "/blog" | "/case-studies" | "/cdn" | "/cdn/caches" | "/cdn/redirects" | "/cdn/routing" | "/cdn/routing/new" | "/contact" | "/cron" | "/deploy/[id]" | "/deployments" | "/deployments/[id]" | "/docs" | "/docs/api-reference" | "/docs/api-reference/[category]/[method]" | "/docs/getting-started" | "/domains" | "/domains/[domain]" | "/features" | "/firewall" | "/functions" | "/integrations" | "/logs" | "/monitoring" | "/network" | "/new" | "/new/upload" | "/observability" | "/preview-unlock" | "/pricing" | "/privacy" | "/product" | "/projects" | "/projects/[project]" | "/projects/[project]/logs" | "/projects/[project]/sandboxes" | "/projects/[project]/sandboxes/[sandboxId]" | "/projects/[project]/settings" | "/projects/[project]/settings/build" | "/projects/[project]/settings/cron" | "/projects/[project]/settings/environment-variables" | "/projects/[project]/settings/functions" | "/projects/[project]/settings/git" | "/projects/[project]/settings/microfrontends" | "/projects/[project]/settings/network" | "/projects/[project]/settings/routing" | "/projects/[project]/settings/secure-compute" | "/projects/[project]/settings/team" | "/projects/[project]/settings/webhooks" | "/regions" | "/sandbox" | "/settings" | "/settings/api-keys" | "/settings/enterprise" | "/settings/notifications" | "/settings/webhooks" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]" | "/solutions" | "/status" | "/storage" | "/storage/[id]" | "/teams" | "/usage" | "/workflows" | "/workflows/runs/[id]"
type AppRouteHandlerRoutes = "/api/blocked" | "/api/composio/connect" | "/api/composio/toolkits" | "/api/git/deploy" | "/api/github/connect" | "/api/github/create-repo" | "/api/github/disconnect" | "/api/github/orgs" | "/api/github/repos" | "/api/github/status" | "/api/gitops/init" | "/api/gitops/project-ci" | "/api/gitops/sync" | "/api/integrations/link" | "/api/preview-unlock" | "/api/projects/[project]/redeploy" | "/api/token" | "/api/zk-enroll" | "/oauth/github/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/cdn" | "/docs" | "/projects/[project]/settings"
type RedirectRoutes = "/dashboard" | "/login" | "/marketplace" | "/signup" | "/team"
type RewriteRoutes = "/cloud/[[...path]]" | "/cloud/v1/zkauth/[[...path]]" | "/ops/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/activity": {}
  "/admin": {}
  "/admin/audit": {}
  "/admin/data": {}
  "/admin/databases": {}
  "/admin/incidents": {}
  "/admin/nodes": {}
  "/admin/teams": {}
  "/api/blocked": {}
  "/api/composio/connect": {}
  "/api/composio/toolkits": {}
  "/api/git/deploy": {}
  "/api/github/connect": {}
  "/api/github/create-repo": {}
  "/api/github/disconnect": {}
  "/api/github/orgs": {}
  "/api/github/repos": {}
  "/api/github/status": {}
  "/api/gitops/init": {}
  "/api/gitops/project-ci": {}
  "/api/gitops/sync": {}
  "/api/integrations/link": {}
  "/api/preview-unlock": {}
  "/api/projects/[project]/redeploy": { "project": string; }
  "/api/token": {}
  "/api/zk-enroll": {}
  "/billing": {}
  "/billing/checkout": {}
  "/blog": {}
  "/case-studies": {}
  "/cdn": {}
  "/cdn/caches": {}
  "/cdn/redirects": {}
  "/cdn/routing": {}
  "/cdn/routing/new": {}
  "/cloud/[[...path]]": { "path"?: string[]; }
  "/cloud/v1/zkauth/[[...path]]": { "path"?: string[]; }
  "/contact": {}
  "/cron": {}
  "/dashboard": {}
  "/deploy/[id]": { "id": string; }
  "/deployments": {}
  "/deployments/[id]": { "id": string; }
  "/docs": {}
  "/docs/api-reference": {}
  "/docs/api-reference/[category]/[method]": { "category": string; "method": string; }
  "/docs/getting-started": {}
  "/domains": {}
  "/domains/[domain]": { "domain": string; }
  "/features": {}
  "/firewall": {}
  "/functions": {}
  "/integrations": {}
  "/login": {}
  "/logs": {}
  "/marketplace": {}
  "/monitoring": {}
  "/network": {}
  "/new": {}
  "/new/upload": {}
  "/oauth/github/callback": {}
  "/observability": {}
  "/ops/[[...path]]": { "path"?: string[]; }
  "/preview-unlock": {}
  "/pricing": {}
  "/privacy": {}
  "/product": {}
  "/projects": {}
  "/projects/[project]": { "project": string; }
  "/projects/[project]/logs": { "project": string; }
  "/projects/[project]/sandboxes": { "project": string; }
  "/projects/[project]/sandboxes/[sandboxId]": { "project": string; "sandboxId": string; }
  "/projects/[project]/settings": { "project": string; }
  "/projects/[project]/settings/build": { "project": string; }
  "/projects/[project]/settings/cron": { "project": string; }
  "/projects/[project]/settings/environment-variables": { "project": string; }
  "/projects/[project]/settings/functions": { "project": string; }
  "/projects/[project]/settings/git": { "project": string; }
  "/projects/[project]/settings/microfrontends": { "project": string; }
  "/projects/[project]/settings/network": { "project": string; }
  "/projects/[project]/settings/routing": { "project": string; }
  "/projects/[project]/settings/secure-compute": { "project": string; }
  "/projects/[project]/settings/team": { "project": string; }
  "/projects/[project]/settings/webhooks": { "project": string; }
  "/regions": {}
  "/sandbox": {}
  "/settings": {}
  "/settings/api-keys": {}
  "/settings/enterprise": {}
  "/settings/notifications": {}
  "/settings/webhooks": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
  "/signup": {}
  "/solutions": {}
  "/status": {}
  "/storage": {}
  "/storage/[id]": { "id": string; }
  "/team": {}
  "/teams": {}
  "/usage": {}
  "/workflows": {}
  "/workflows/runs/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/cdn": never
  "/docs": never
  "/projects/[project]/settings": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
