// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity">> = Specific
  const handler = {} as typeof import("../../app/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data">> = Specific
  const handler = {} as typeof import("../../app/admin/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/databases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/databases">> = Specific
  const handler = {} as typeof import("../../app/admin/databases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/incidents">> = Specific
  const handler = {} as typeof import("../../app/admin/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/nodes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/nodes">> = Specific
  const handler = {} as typeof import("../../app/admin/nodes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/teams">> = Specific
  const handler = {} as typeof import("../../app/admin/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/billing/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing/checkout">> = Specific
  const handler = {} as typeof import("../../app/billing/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies">> = Specific
  const handler = {} as typeof import("../../app/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cdn/caches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cdn/caches">> = Specific
  const handler = {} as typeof import("../../app/cdn/caches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cdn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cdn">> = Specific
  const handler = {} as typeof import("../../app/cdn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cdn/redirects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cdn/redirects">> = Specific
  const handler = {} as typeof import("../../app/cdn/redirects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cdn/routing/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cdn/routing/new">> = Specific
  const handler = {} as typeof import("../../app/cdn/routing/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cdn/routing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cdn/routing">> = Specific
  const handler = {} as typeof import("../../app/cdn/routing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cron/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cron">> = Specific
  const handler = {} as typeof import("../../app/cron/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/deploy/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deploy/[id]">> = Specific
  const handler = {} as typeof import("../../app/deploy/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/deployments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deployments/[id]">> = Specific
  const handler = {} as typeof import("../../app/deployments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/deployments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deployments">> = Specific
  const handler = {} as typeof import("../../app/deployments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/api-reference/[category]/[method]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/api-reference/[category]/[method]">> = Specific
  const handler = {} as typeof import("../../app/docs/api-reference/[category]/[method]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/api-reference/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/api-reference">> = Specific
  const handler = {} as typeof import("../../app/docs/api-reference/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/getting-started/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/getting-started">> = Specific
  const handler = {} as typeof import("../../app/docs/getting-started/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/domains/[domain]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/domains/[domain]">> = Specific
  const handler = {} as typeof import("../../app/domains/[domain]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/domains/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/domains">> = Specific
  const handler = {} as typeof import("../../app/domains/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/firewall/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/firewall">> = Specific
  const handler = {} as typeof import("../../app/firewall/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/functions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/functions">> = Specific
  const handler = {} as typeof import("../../app/functions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations">> = Specific
  const handler = {} as typeof import("../../app/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logs">> = Specific
  const handler = {} as typeof import("../../app/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring">> = Specific
  const handler = {} as typeof import("../../app/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/network">> = Specific
  const handler = {} as typeof import("../../app/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new">> = Specific
  const handler = {} as typeof import("../../app/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/new/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new/upload">> = Specific
  const handler = {} as typeof import("../../app/new/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/observability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/observability">> = Specific
  const handler = {} as typeof import("../../app/observability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/preview-unlock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview-unlock">> = Specific
  const handler = {} as typeof import("../../app/preview-unlock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product">> = Specific
  const handler = {} as typeof import("../../app/product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/logs">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/sandboxes/[sandboxId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/sandboxes/[sandboxId]">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/sandboxes/[sandboxId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/sandboxes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/sandboxes">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/sandboxes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/build/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/build">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/build/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/cron/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/cron">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/cron/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/environment-variables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/environment-variables">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/environment-variables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/functions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/functions">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/functions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/git/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/git">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/git/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/microfrontends/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/microfrontends">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/microfrontends/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/network">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/routing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/routing">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/routing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/secure-compute/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/secure-compute">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/secure-compute/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/team">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/webhooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[project]/settings/webhooks">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/webhooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/regions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/regions">> = Specific
  const handler = {} as typeof import("../../app/regions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sandbox">> = Specific
  const handler = {} as typeof import("../../app/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/api-keys">> = Specific
  const handler = {} as typeof import("../../app/settings/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/enterprise">> = Specific
  const handler = {} as typeof import("../../app/settings/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/notifications">> = Specific
  const handler = {} as typeof import("../../app/settings/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/webhooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/webhooks">> = Specific
  const handler = {} as typeof import("../../app/settings/webhooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../app/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-up/[[...sign-up]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/[[...sign-up]]">> = Specific
  const handler = {} as typeof import("../../app/sign-up/[[...sign-up]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions">> = Specific
  const handler = {} as typeof import("../../app/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/status">> = Specific
  const handler = {} as typeof import("../../app/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/storage/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/storage/[id]">> = Specific
  const handler = {} as typeof import("../../app/storage/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/storage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/storage">> = Specific
  const handler = {} as typeof import("../../app/storage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams">> = Specific
  const handler = {} as typeof import("../../app/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/usage">> = Specific
  const handler = {} as typeof import("../../app/usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows">> = Specific
  const handler = {} as typeof import("../../app/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/workflows/runs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows/runs/[id]">> = Specific
  const handler = {} as typeof import("../../app/workflows/runs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blocked/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blocked">> = Specific
  const handler = {} as typeof import("../../app/api/blocked/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/composio/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/composio/connect">> = Specific
  const handler = {} as typeof import("../../app/api/composio/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/composio/toolkits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/composio/toolkits">> = Specific
  const handler = {} as typeof import("../../app/api/composio/toolkits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/git/deploy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/git/deploy">> = Specific
  const handler = {} as typeof import("../../app/api/git/deploy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/connect">> = Specific
  const handler = {} as typeof import("../../app/api/github/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/create-repo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/create-repo">> = Specific
  const handler = {} as typeof import("../../app/api/github/create-repo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/disconnect">> = Specific
  const handler = {} as typeof import("../../app/api/github/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/orgs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/orgs">> = Specific
  const handler = {} as typeof import("../../app/api/github/orgs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/repos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/repos">> = Specific
  const handler = {} as typeof import("../../app/api/github/repos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/github/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/status">> = Specific
  const handler = {} as typeof import("../../app/api/github/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gitops/init/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gitops/init">> = Specific
  const handler = {} as typeof import("../../app/api/gitops/init/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gitops/project-ci/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gitops/project-ci">> = Specific
  const handler = {} as typeof import("../../app/api/gitops/project-ci/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gitops/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gitops/sync">> = Specific
  const handler = {} as typeof import("../../app/api/gitops/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/link">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-unlock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-unlock">> = Specific
  const handler = {} as typeof import("../../app/api/preview-unlock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[project]/redeploy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[project]/redeploy">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[project]/redeploy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/token">> = Specific
  const handler = {} as typeof import("../../app/api/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/zk-enroll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zk-enroll">> = Specific
  const handler = {} as typeof import("../../app/api/zk-enroll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/oauth/github/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/oauth/github/callback">> = Specific
  const handler = {} as typeof import("../../app/oauth/github/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cdn/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cdn">> = Specific
  const handler = {} as typeof import("../../app/cdn/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[project]/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects/[project]/settings">> = Specific
  const handler = {} as typeof import("../../app/projects/[project]/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
