var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/gitops/sync/route.js")
R.c("server/chunks/lib_composio_ts_1qgq01_._.js")
R.c("server/chunks/[root-of-the-server]__0dnul9n._.js")
R.c("server/chunks/[root-of-the-server]__193d3s6._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_gitops_sync_route_actions_12o5bja.js")
R.m(7661)
module.exports=R.m(7661).exports
