var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/gitops/project-ci/route.js")
R.c("server/chunks/lib_composio_ts_1qgq01_._.js")
R.c("server/chunks/[root-of-the-server]__0dwkwly._.js")
R.c("server/chunks/[root-of-the-server]__193d3s6._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_gitops_project-ci_route_actions_0jz8h9g.js")
R.m(97594)
module.exports=R.m(97594).exports
