[package]
name = "hive-p2p"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fluid-tunnel = { workspace = true }
tokio = { workspace = true }
bytes = "1"
anyhow = { workspace = true }
tracing = { workspace = true }
iroh = "1"
serde_json = { workspace = true }

[[bin]]
name = "p2p-demo"
path = "src/bin/p2p_demo.rs"
