// Stand-in for what a real `open-next build` emits at this exact path: a
// standalone Node-compatible HTTP server bundle that binds $PORT. This file is
// checked in (rather than generated by actually running the Next.js/OpenNext
// toolchain in this fixture) purely so the PLATFORM's own adapter-detection
// code (`adapter_manifest` in hive-cloud/git.rs) has a real file to find at
// the exact path it checks — the platform logic under test only cares that
// this path exists and is a runnable server, not how it was produced. It is,
// however, a REAL working server: `bun run .open-next/server-functions/default/index.mjs`
// actually boots and serves requests, exactly like the genuine OpenNext output
// would under the Bun runtime this fixture selects via vercel.json.
import http from "node:http";

const port = Number(process.env.PORT || 3000);
http
  .createServer((req, res) => {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ msg: "hello from an OpenNext server function (Bun runtime)", path: req.url }));
  })
  .listen(port, "127.0.0.1", () => console.log(`listening on ${port}`));
